version: '3.7'
networks:
  ES:

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - ES
    environment:
      - discovery.type=single-node
      - node.name=single-node-elastic
    volumes:
      - ./volumes/data:/usr/share/elasticsearch/data
      - ./volumes/config:/usr/share/elasticsearch/config
      - ./volumes/plugins:/usr/share/elasticsearch/plugins

  kibana:
    container_name: kibana
    image: kibana:7.5.2
    ports:
      - 5601:5601
    networks:
      - ES
